/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package memorycards;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Korisnik
 */
public class Level extends javax.swing.JFrame {

    /**
     * Creates new form Level
     */
    public Level() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Exit = new javax.swing.JButton();
        Minimize = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Quit = new javax.swing.JLabel();
        Easy = new javax.swing.JLabel();
        Normal = new javax.swing.JLabel();
        Hard = new javax.swing.JLabel();
        Menu = new javax.swing.JLabel();
        easyMess = new javax.swing.JLabel();
        normalMess = new javax.swing.JLabel();
        hardMess = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(java.awt.Color.gray);
        jPanel1.setForeground(new java.awt.Color(153, 255, 153));

        Exit.setBackground(java.awt.Color.darkGray);
        Exit.setFont(new java.awt.Font("BankGothic Lt BT", 0, 18)); // NOI18N
        Exit.setForeground(java.awt.Color.red);
        Exit.setText("X");
        Exit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitMouseExited(evt);
            }
        });
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        Minimize.setBackground(java.awt.Color.darkGray);
        Minimize.setFont(new java.awt.Font("BankGothic Lt BT", 1, 18)); // NOI18N
        Minimize.setForeground(java.awt.Color.red);
        Minimize.setText("-");
        Minimize.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MinimizeMouseExited(evt);
            }
        });

        jLabel1.setBackground(java.awt.Color.gray);
        jLabel1.setFont(new java.awt.Font("BankGothic Lt BT", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 255, 153));
        jLabel1.setText("Memory Cards");

        Quit.setBackground(java.awt.Color.gray);
        Quit.setFont(new java.awt.Font("BankGothic Lt BT", 0, 24)); // NOI18N
        Quit.setForeground(new java.awt.Color(153, 255, 153));
        Quit.setText("Quit");
        Quit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Quit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QuitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                QuitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                QuitMouseExited(evt);
            }
        });

        Easy.setBackground(java.awt.Color.gray);
        Easy.setFont(new java.awt.Font("BankGothic Lt BT", 0, 36)); // NOI18N
        Easy.setForeground(new java.awt.Color(153, 255, 153));
        Easy.setText("Easy");
        Easy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Easy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EasyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EasyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EasyMouseExited(evt);
            }
        });

        Normal.setBackground(java.awt.Color.gray);
        Normal.setFont(new java.awt.Font("BankGothic Lt BT", 0, 36)); // NOI18N
        Normal.setForeground(new java.awt.Color(153, 255, 153));
        Normal.setText("Normal");
        Normal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Normal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NormalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NormalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NormalMouseExited(evt);
            }
        });

        Hard.setBackground(java.awt.Color.gray);
        Hard.setFont(new java.awt.Font("BankGothic Lt BT", 0, 36)); // NOI18N
        Hard.setForeground(new java.awt.Color(153, 255, 153));
        Hard.setText("Hard");
        Hard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Hard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HardMouseExited(evt);
            }
        });

        Menu.setBackground(java.awt.Color.gray);
        Menu.setFont(new java.awt.Font("BankGothic Lt BT", 0, 24)); // NOI18N
        Menu.setForeground(new java.awt.Color(153, 255, 153));
        Menu.setText("Menu");
        Menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MenuMouseExited(evt);
            }
        });

        easyMess.setBackground(java.awt.Color.gray);
        easyMess.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        easyMess.setForeground(new java.awt.Color(153, 255, 153));

        normalMess.setBackground(java.awt.Color.gray);
        normalMess.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        normalMess.setForeground(new java.awt.Color(153, 255, 153));

        hardMess.setBackground(java.awt.Color.gray);
        hardMess.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        hardMess.setForeground(new java.awt.Color(153, 255, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Menu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Quit))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                        .addComponent(Minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(easyMess, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(hardMess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Normal))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Easy)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Hard)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(normalMess, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Exit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Minimize, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1))
                .addGap(89, 89, 89)
                .addComponent(Easy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Normal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(normalMess, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(easyMess, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Hard)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hardMess, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Quit)
                    .addComponent(Menu))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_ExitMouseClicked

    private void ExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseEntered
        Exit.setBackground(Color.GRAY);
    }//GEN-LAST:event_ExitMouseEntered

    private void ExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseExited
        Exit.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_ExitMouseExited

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitActionPerformed

    private void MinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_MinimizeMouseClicked

    private void MinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeMouseEntered
        Minimize.setBackground(Color.GRAY);
    }//GEN-LAST:event_MinimizeMouseEntered

    private void MinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeMouseExited
        Minimize.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_MinimizeMouseExited

    private void QuitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuitMouseClicked
        int quit = JOptionPane.showConfirmDialog(null, "Are u sure?", "Quit message", JOptionPane.YES_NO_OPTION);
        if(JOptionPane.NO_OPTION==quit)
        {
        }else
        {
            System.exit(0);
        }
    }//GEN-LAST:event_QuitMouseClicked

    private void QuitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuitMouseEntered
        Quit.setText(">Don't");
    }//GEN-LAST:event_QuitMouseEntered

    private void QuitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuitMouseExited
        Quit.setText("Quit");
    }//GEN-LAST:event_QuitMouseExited

    private void EasyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EasyMouseClicked
        BoardA A = new BoardA();
        A.setPreferredSize(new Dimension(500,500));
        A.setVisible(true);
        A.pack();
        A.setLocationRelativeTo(null);
        A.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_EasyMouseClicked

    private void EasyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EasyMouseEntered
        Easy.setText(Easy.getText()+"<");
        easyMess.setText("6 pairs");
    }//GEN-LAST:event_EasyMouseEntered

    private void EasyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EasyMouseExited
        Easy.setText("Easy");
        easyMess.setText("");
    }//GEN-LAST:event_EasyMouseExited

    private void NormalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NormalMouseEntered
        Normal.setText(">"+Normal.getText());
        normalMess.setText("10 pairs");
    }//GEN-LAST:event_NormalMouseEntered

    private void NormalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NormalMouseExited
        Normal.setText("Normal");
        normalMess.setText("");
    }//GEN-LAST:event_NormalMouseExited

    private void HardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HardMouseEntered
        Hard.setText(Hard.getText()+"<");
        hardMess.setText("18 pairs");
    }//GEN-LAST:event_HardMouseEntered

    private void HardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HardMouseExited
        Hard.setText("Hard");
        hardMess.setText("");
    }//GEN-LAST:event_HardMouseExited

    private void NormalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NormalMouseClicked
        BoardB B = new BoardB();
        B.setPreferredSize(new Dimension(500,500));
        B.setVisible(true);
        B.pack();
        B.setLocationRelativeTo(null);
        B.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_NormalMouseClicked

    private void HardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HardMouseClicked
        BoardC C = new BoardC();
        C.setPreferredSize(new Dimension(500,500));
        C.setVisible(true);
        C.pack();
        C.setLocationRelativeTo(null);
        C.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        
        String filepath = "music\\\\goodbadugly.wav";
        Music musicObject = new Music();
        musicObject.playMusic(filepath); 
    }//GEN-LAST:event_HardMouseClicked

    private void MenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuMouseClicked
        Entry e = new Entry();
        e.setVisible(true);
        e.pack();
        e.setLocationRelativeTo(null);
        e.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_MenuMouseClicked

    private void MenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuMouseEntered
        Menu.setText(Menu.getText()+"<");
    }//GEN-LAST:event_MenuMouseEntered

    private void MenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuMouseExited
        Menu.setText("Menu");
    }//GEN-LAST:event_MenuMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Level.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Level.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Level.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Level.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Level().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Easy;
    private javax.swing.JButton Exit;
    private javax.swing.JLabel Hard;
    private javax.swing.JLabel Menu;
    private javax.swing.JButton Minimize;
    private javax.swing.JLabel Normal;
    private javax.swing.JLabel Quit;
    private javax.swing.JLabel easyMess;
    private javax.swing.JLabel hardMess;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel normalMess;
    // End of variables declaration//GEN-END:variables
}
